[workspace]
# Generate Cargo.toml, Cargo.lock, and CHANGELOG.md release changes locally.
changelog_update = true
dependencies_update = false
semver_check = true

[changelog]
protect_breaking_commits = true
sort_commits = "oldest"
