default: server

server:
	cd server && just run

server-check:
	cd server && just check

server-explicit:
	cd server-explicit && just run

server-explicit-check:
	cd server-explicit && just check

web:
	cd web && npm run dev

web-build:
	cd web && npm run build
